"""The Python half of the encoder. src/features.ts is the other half.

These two files must produce bit-identical vectors from identical raw inputs, and
nothing in either language will tell you when they stop doing so -- every value is
a float, so a shuffled or subtly re-bucketed vector looks perfectly healthy and
simply makes the model wrong forever. scripts/parity.ts is the only real defence:
it pushes ~500 RAW rows (a date string and millimetres, not a pre-encoded vector)
through both and demands agreement to 1e-9.

So this file is written as a deliberate line-by-line mirror of the TypeScript
rather than as idiomatic Python. Where the two could differ, the TS behaviour
wins:

  * `dow` is 0=Sunday, matching `new Date(...).getUTCDay()`, NOT Python's
    Monday-is-0 convention.
  * A missing measurement encodes as NaN, not as a sentinel or an imputed mean.
    LightGBM routes NaN by the split's default direction and gbdt.ts reproduces
    that routing exactly, so "unknown" survives the round trip.
  * Bucket edges arrive as arguments, never as literals. They live in the
    artifact, and hardcoding them here would let a retrain silently disagree with
    a deployed Worker.

There are two encoders in here, and that is on purpose: `encode_one` is the
scalar mirror used to generate golden vectors, and `build_matrix` is the
vectorised path used to build 5M training rows. `check_paths_agree` asserts they
produce the same answer, because a golden vector generated by a code path the
training set never used would prove nothing about the training set.
"""

from __future__ import annotations

import datetime as dt
import math

import numpy as np
import pandas as pd

from . import paths, weather
from .panel import connect

# Order IS the contract. src/features.ts declares the same list and refuses to
# run against an artifact whose order disagrees.
FEATURE_NAMES = [
    "hour",
    "dow",
    "is_weekend",
    "is_holiday",
    "month",
    "temp_c",
    "precip_bucket",
    "wind_kmh",
    "dew_c",
    "night_precip_bucket",
    "st_morning_share",
    "st_log_level",
    "st_net_balance",
]

DEFAULT_ENCODERS = {
    "precipDryMaxMm": paths.PRECIP_DRY_MAX_MM,
    "precipWetMinMm": paths.PRECIP_WET_MIN_MM,
    "probBumpThreshold": paths.PROB_BUMP_THRESHOLD,
}


# --------------------------------------------------------------------------
# Quebec statutory holidays -- a port of src/holidays.ts, computed not listed.
# --------------------------------------------------------------------------


def easter_sunday(year: int) -> dt.date:
    """Anonymous Gregorian computus (Meeus), same arithmetic as holidays.ts."""
    a = year % 19
    b, c = divmod(year, 100)
    d, e = divmod(b, 4)
    f = (b + 8) // 25
    g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30
    i, k = divmod(c, 4)
    ll = (32 + 2 * e + 2 * i - h - k) % 7
    m = (a + 11 * h + 22 * ll) // 451
    month = (h + ll - 7 * m + 114) // 31
    day = ((h + ll - 7 * m + 114) % 31) + 1
    return dt.date(year, month, day)


def _nth_monday(year: int, month: int, n: int) -> dt.date:
    first = dt.date(year, month, 1)
    # (8 - weekday) % 7 lands on the first Monday, where weekday is 0=Sunday as
    # in JS. Python's weekday() is Monday-based, hence the conversion.
    js_dow = (first.weekday() + 1) % 7
    return first + dt.timedelta(days=((8 - js_dow) % 7) + (n - 1) * 7)


def quebec_holidays(year: int) -> dict[str, str]:
    out: dict[str, str] = {}

    def add(d: dt.date, name: str) -> None:
        out[d.isoformat()] = name

    add(dt.date(year, 1, 1), "New Year's Day")
    easter = easter_sunday(year)
    # The statute grants Good Friday OR Easter Monday at the employer's choice,
    # so traffic is light on both -- holidays.ts counts both and so does this.
    add(easter - dt.timedelta(days=2), "Good Friday")
    add(easter + dt.timedelta(days=1), "Easter Monday")
    may25 = dt.date(year, 5, 25)
    js_dow = (may25.weekday() + 1) % 7
    back = ((js_dow + 6) % 7) or 7  # Monday strictly preceding May 25
    add(may25 - dt.timedelta(days=back), "National Patriots' Day")
    add(dt.date(year, 6, 24), "Fête nationale")
    jul1 = dt.date(year, 7, 1)
    add(dt.date(year, 7, 2) if (jul1.weekday() + 1) % 7 == 0 else jul1, "Canada Day")
    add(_nth_monday(year, 9, 1), "Labour Day")
    add(_nth_monday(year, 10, 2), "Thanksgiving")
    add(dt.date(year, 12, 25), "Christmas Day")
    return out


_HOLIDAY_CACHE: dict[int, dict[str, str]] = {}


def holiday_name(date_str: str) -> str | None:
    year = int(date_str[:4])
    if year not in _HOLIDAY_CACHE:
        _HOLIDAY_CACHE[year] = quebec_holidays(year)
    return _HOLIDAY_CACHE[year].get(date_str)


# --------------------------------------------------------------------------
# Encoding
# --------------------------------------------------------------------------


def dow_of(date_str: str) -> int:
    """0=Sunday..6=Saturday, matching Date.getUTCDay()."""
    y, m, d = (int(x) for x in date_str.split("-"))
    return (dt.date(y, m, d).weekday() + 1) % 7


def precip_bucket(mm: float | None, dry_max: float, wet_min: float) -> float:
    if mm is None or (isinstance(mm, float) and math.isnan(mm)):
        return math.nan  # uninformative; the tree's default_left routes it
    return 0.0 if mm < dry_max else (1.0 if mm <= wet_min else 2.0)


def promote_for_prob(bucket: float, prob: float | None, threshold: float) -> float:
    # NaN never equals 0, so an unknown bucket is never promoted -- the same
    # behaviour the TS gets for free from `bucket === 0`.
    if bucket == 0.0 and prob is not None and not math.isnan(prob) and prob >= threshold:
        return 1.0
    return bucket


def encode_one(raw: dict, enc: dict, prof: dict) -> list[float]:
    """Scalar mirror of `encode()` in src/features.ts, field for field.

    `prof` uses the artifact's camelCase keys (morningShare / logLevel /
    netBalance) rather than the DataFrame's snake_case, because src/features.ts
    reads `a.station.morningShare` -- keeping the same spelling here means the
    mirror can be checked by eye against the TypeScript.
    """
    date = raw["date"]
    d = dow_of(date)
    month = int(date[5:7])
    bucket = promote_for_prob(
        precip_bucket(raw.get("precipMm"), enc["precipDryMaxMm"], enc["precipWetMinMm"]),
        raw.get("precipProb"),
        enc["probBumpThreshold"],
    )
    nan = math.nan
    return [
        float(raw["hour"]),
        float(d),
        1.0 if d in (0, 6) else 0.0,
        1.0 if holiday_name(date) else 0.0,
        float(month),
        float(raw["tempC"]) if raw.get("tempC") is not None else nan,
        bucket,
        float(raw["windKmh"]) if raw.get("windKmh") is not None else nan,
        float(raw["dewC"]) if raw.get("dewC") is not None else nan,
        # No probability promotion on the night bucket: precip_prob is a
        # morning-window signal. bixi-predictor draws the same distinction.
        precip_bucket(raw.get("nightPrecipMm"), enc["precipDryMaxMm"], enc["precipWetMinMm"]),
        float(prof["morningShare"]),
        float(prof["logLevel"]),
        float(prof["netBalance"]),
    ]


def build_matrix(con=None, enc: dict | None = None) -> pd.DataFrame:
    """The full training matrix: features, both targets, and the Poisson offset.

    Weather joins as an INNER join on purpose. A station-hour with no weather row
    would otherwise enter training with every meteorological feature NaN, and the
    trees would happily carve out a "weather is unknown" regime that can never
    occur at serving time.
    """
    enc = enc or DEFAULT_ENCODERS
    own = con is None
    con = con or connect()
    try:
        weather.ensure_table(con)
        con.execute(
            f"""
            CREATE OR REPLACE TEMP TABLE night_precip AS
              WITH nights AS (
                -- 20:00-02:00 leading INTO the target date. Hourly precipitation
                -- at label H covers [H-1, H), so the evening half is labels
                -- 21..23 of the previous day. demand.ts uses this exact window.
                SELECT date + 1 AS date, precip_mm FROM weather_hourly WHERE hour IN (21, 22, 23)
                UNION ALL
                SELECT date, precip_mm FROM weather_hourly WHERE hour IN (0, 1, 2)
              )
              SELECT date, SUM(precip_mm) AS night_mm FROM nights GROUP BY 1;
            """
        )
        df = con.execute(
            """
            SELECT p.station, p.date, p.hour::INTEGER AS hour, p.dep, p.arr,
                   dayofweek(p.date) AS dow, month(p.date) AS month,
                   w.temp_c, w.precip_mm, w.wind_kmh, w.dew_c, n.night_mm,
                   s.morning_share AS st_morning_share,
                   s.log_level     AS st_log_level,
                   s.net_balance   AS st_net_balance
              FROM panel p
              JOIN weather_hourly w ON w.date = p.date AND w.hour = p.hour
              JOIN night_precip   n ON n.date = p.date
              JOIN station_profile s ON s.name = p.station
             ORDER BY p.date, p.station, p.hour
            """
        ).df()
    finally:
        if own:
            con.close()

    dry, wet = enc["precipDryMaxMm"], enc["precipWetMinMm"]

    def bucketize(col: pd.Series) -> np.ndarray:
        v = col.to_numpy(dtype=float)
        out = np.where(v < dry, 0.0, np.where(v <= wet, 1.0, 2.0))
        return np.where(np.isnan(v), np.nan, out)

    df["is_weekend"] = df["dow"].isin((0, 6)).astype(float)
    # Explicit strftime, NOT astype(str). DuckDB hands back a datetime64, whose
    # string form is "2024-04-21 00:00:00" -- which parses as a year just fine and
    # then matches no holiday key at all. That failure is silent: is_holiday comes
    # out uniformly zero and the model simply never learns the effect.
    df["date_str"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
    # Holidays are computed once per distinct date, not once per row -- there are
    # ~430 dates and 5.2M rows.
    hol = {d: (1.0 if holiday_name(d) else 0.0) for d in df["date_str"].unique()}
    df["is_holiday"] = df["date_str"].map(hol).to_numpy()
    if df["is_holiday"].sum() == 0:
        raise AssertionError("is_holiday is uniformly zero -- the date/holiday join is broken")
    df["precip_bucket"] = bucketize(df["precip_mm"])
    df["night_precip_bucket"] = bucketize(df["night_mm"])
    for c in ("hour", "dow", "month", "temp_c", "wind_kmh", "dew_c"):
        df[c] = df[c].astype(float)

    # Training never sees a precipitation probability -- the archive API has no
    # such field -- so the promotion rule is a no-op here and is applied only at
    # serving time. That asymmetry is the point: it keeps the ENCODER identical
    # while letting the forecast-only signal still be used.
    return df


def check_paths_agree(df: pd.DataFrame, enc: dict, n: int = 2000, seed: int = 7) -> None:
    """The vectorised matrix and the scalar encoder must not drift apart.

    Golden vectors come from `encode_one`; the model is trained on `build_matrix`.
    If those two ever disagree, parity would pass against a model that was fit on
    something else -- the gate would be green and meaningless.
    """
    rng = np.random.default_rng(seed)
    idx = rng.choice(len(df), size=min(n, len(df)), replace=False)
    mat = df[FEATURE_NAMES].to_numpy(dtype=float)
    worst = 0.0
    for i in idx:
        r = df.iloc[i]
        got = encode_one(
            {
                "date": r["date_str"],
                "hour": r["hour"],
                "tempC": r["temp_c"],
                "precipMm": r["precip_mm"],
                "precipProb": None,
                "windKmh": r["wind_kmh"],
                "dewC": r["dew_c"],
                "nightPrecipMm": r["night_mm"],
            },
            enc,
            {
                "morningShare": r["st_morning_share"],
                "logLevel": r["st_log_level"],
                "netBalance": r["st_net_balance"],
            },
        )
        a, b = np.asarray(got, dtype=float), mat[i]
        both_nan = np.isnan(a) & np.isnan(b)
        diff = np.where(both_nan, 0.0, np.abs(a - b))
        worst = max(worst, float(np.nanmax(diff)))
    if worst > 1e-12:
        raise AssertionError(f"scalar and vectorised encoders disagree by {worst:g}")
    print(f"[features] scalar/vectorised encoders agree on {len(idx)} sampled rows (max diff {worst:g})")


if __name__ == "__main__":
    d = build_matrix()
    print(f"[features] {len(d):,} rows x {len(FEATURE_NAMES)} features")
    check_paths_agree(d, DEFAULT_ENCODERS)
    print(d[FEATURE_NAMES].describe().T.round(3).to_string())
